Prog 49 rework button change variables
felixkru/PP2023 pull request #18
Opened 2023-09-28 21:25 UTC by lk24dx

Rework des Buttons zum Switchen der Variablen. Der Button wird jetzt über einen direkten DOM-Zugriff disabled. Ich hatte hierbei Probleme mit Globalen-Statusvariablen.

2023-10-01 10:26 UTC, DarianG19 requested changes

2023-10-01 10:26 UTC, DarianG19 commented on pp-2023/src/app/globals.css
> -  background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='3' fill='rgba(116, 115, 234, 1)'/></svg>");
Jetzt hast du aber das gesamte Styling des Buttons rausgenommen, das find ich nicht so gut

2023-10-01 10:26 UTC, DarianG19 commented on pp-2023/src/app/globals.css
> -  background-image: url("data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='-4 -4 8 8'%3e%3ccircle r='3' fill='rgba(116, 115, 234, 1)'/></svg>");
Wenn du das so ändern könntest, dass das Styling auf den Status der Variable keinen Einfluss hat, wäre das gut

2023-10-01 13:55 UTC, lk24dx commented
ich habe einmal dein css wieder rein genommen. Aber bitte den Switch local-remote überarbeiten. Und keine Bootstrap-Klassen direkt stylen.

2023-10-04 14:53 UTC, DarianG19 approved these changes

2023-10-04 14:54 UTC, DarianG19 commented on pp-2023/src/app/kmeans/switch-variables.js
> +                    <label className="formform-check-label"
bitte das noch ändern

2023-10-04 19:42 UTC, merged